### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by cmsalmeida** [Trust-Code/python-boleto#11]
Traceback (most recent call last):
  File "/tmp/tmpc_zO2q", line 14, in <module>
    exec(compile(f.read(), '/home/ubuntu/odoo100/src/python-boleto/setup.py', 'exec'))
  File "/home/ubuntu/odoo100/src/python-boleto/setup.py", line 75, in <module>
    'sphinx'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/develop.py", line 36, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/develop.py", line 137, in install_for_development
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 727, in process_distribution
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/develop.py", line 172, in install_egg_scripts
  File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1237: ordinal not in range(128)

**Comment by danimaribeiro** [comment]
Quais os passos para reproduzir?

**Comment by cmsalmeida** [comment]
Era o locale, resolvi quando instalei o pt_BR, obrigado
